---
sudo: required

services:
  - docker

language: java
jdk: openjdk11

before_install:
  - if [ "$TRAVIS_BRANCH" != "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      git checkout $TRAVIS_BRANCH;
    fi
  - cp .maven.settings.xml $HOME/.m2/settings.xml
  - mvn fmt:check
  - export TZ=Europe/London

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - travis_wait mvn clean install

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      ./scripts/docker_push.sh;
    fi

cache:
  directories:
    - $HOME/.m2

