version: '2.1'
services:
  redis:
    container_name: redis-case-it
    image: redis:3.2.9
    ports:
    - "17379:6379"
  rabbitmq:
    container_name: rabbitmq-case-it
    image: rabbitmq:3.6.10-management
    ports:
    - "34369:4369"
    - "55672:25672"
    - "35671:5671"
    - "35672:5672"
    - "46671:15671"
    - "46672:15672"

