info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: INFO
    org.springframework: INFO
  profile: DEV
  useJson: true

management:
  health:
    rabbit:
      enabled: false 
  endpoints:
    enabled-by-default: true
    web:
      base-path: /
  info:
    env:
      enabled: true 
    build:
      enabled: true 
    git:
      mode: SIMPLE 
      enabled: true 
    defaults:
      enabled: true
  endpoint:
    auditevents:
      enabled: false
    beans:
      enabled: false
    caches:
      enabled: false
    conditions:
      enabled: false
    configprops:
      enabled: false
    env:
      enabled: false
    flyway:
      enabled: false
    health:
      enabled: false
    httptrace:
      enabled: false
    integrationgraph:
      enabled: false
    loggers:
      enabled: false
    liquibase:
      enabled: false
    metrics:
      enabled: false
    mappings:
      enabled: false
    scheduledtasks:
      enabled: false
    sessions:
      enabled: false
    shutdown:
      enabled: false
    threaddump:
      enabled: false
    heapdump:
      enabled: false
    jolokia:
      enabled: false
    logfile:
      enabled: false
    prometheus:
      enabled: false

server:
  port: 8071

spring:
  mvc:
    servlet:
      path: /
  security:
    user:
      name: admin
      password: secret
  output:
    ansi:
      enabled: never
  application:
    name: ONS RespondentHomeService

rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 35672
  virtualhost: /

queueconfig:
  event-exchange: events
  dead-letter-exchange: events.deadletter.exchange
  case-queue: case.rh.case
  case-queue-DLQ: case.rh.case.dlq
  case-routing-key: event.case.update
  uac-queue: case.rh.uac
  uac-queue-DLQ: case.rh.uac.dlq
  uac-routing-key: event.uac.update
  response-authentication-routing-key: event.response.authentication
  qid-filter-prefixes:
     - 11
     - 12
     - 13
     - 14

messaging:
  mismatchedQueuesFatal: true
  backoffInitial: 5000
  backoffMultiplier: 3
  backoffMax: 45000
  consumingThreads: 1
  conMaxAttempts: 3
  prefetchCount: 1

swagger-settings:
  swagger-ui-active: true
  group-name: respondenthome-api
  title: RespondentHomeService
  description: API for ${project.artifactId}
  version: ${project.version}

cloudStorage:
  caseSchemaName: case
  uacSchemaName: uac
  backoffInitial: 100
  backoffMultiplier: 1.2
  backoffMax: 16000
  backoffMaxAttempts: 30
