liquibase:
  url: jdbc:postgresql://localhost:15432/postgres

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres

rabbitmq:
  host: localhost
  port: 35672

schedules:
  validation-schedule-delay-milli-seconds: 1000
  distribution-schedule-delay-milli-seconds: 1000
