info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: DEBUG
    org.springframework: ERROR
  profile: DEV
  useJson: false

  #security:
  # basic:
  #   enabled: false
  #   realm: sdc
  # user:
  #   name: admin
  #   password: secret

management:
  security:
    roles: SUPERUSER
    enabled: true
  health:
    rabbit:
      enabled: false

server:
  port: 8171
  servlet-path: /

endpoints:
  enabled: true
  info:
    enabled: true
    sensitive: false

spring:
  security:
    user:
      name: admin
      password: secret
  output:
    ansi:
      enabled: never
  application:
    name: ONS RespondentHomeService
    #  datasource:
    # url: jdbc:postgresql://localhost:6432/postgres
    # username: postgres
    # password: postgres
    # driverClassName: org.postgresql.Driver
    # continue-on-error: true
    tomcat:
      initial-size: 5
      max-active: 10
      max-idle: 5
      min-idle: 3
  zipkin:
    baseUrl: http://localhost:9411
    enabled: false

    #data-grid:
    #address: localhost:7379
    #list-time-to-live-seconds: 60
    #list-time-to-wait-seconds: 60
    #report-lock-time-to-live-seconds: 300

redelivery-policy:
  maxRedeliveries: 10
  initialRedeliveryDelay: 1000
  redeliveryDelay: 1000

rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 6672
  virtualhost: /

messaging:
  backoffInitial: 5000
  backoffMultiplier: 3
  backoffMax: 45000
  consumingThreads: 1
  pubMaxAttempts: 3
  conMaxAttempts: 3
  prefetchCount: 10
  txSize: 1

report-settings:
  cron-expression: "0 * * * * *"

swagger-settings:
  swagger-ui-active: true
  group-name: respondenthome-api
  title: RespondentHomeService
  description: API for ${project.artifactId}
  version: ${project.version}

retries:
  maxAttempts: 3
  backoff: 5000
