info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: INFO
    org.springframework: INFO
  profile: DEV
  useJson: true

collectionExerciseId : 34d7f3bb-91c9-45d0-bb2d-90afce4fc790

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: info, health
  endpoint:
    info:
      enabled: true 
    health:
      enabled: true
  metrics:
    tags:
      application: RespondentHomeService
      pod: ${HOSTNAME}
    export:
      stackdriver:
        project-id: ${GOOGLE_CLOUD_PROJECT}
        enabled: true
        step: PT2M

server:
  port: 8071
  shutdown: graceful
  undertow:
    threads:
      worker: 40
      io: 6

spring:
  mvc:
    servlet:
      path: /
  security:
    user:
      name: admin
      password: secret
  output:
    ansi:
      enabled: never
  application:
    name: ONS RespondentHomeService
  lifecycle:
    timeout-per-shutdown-phase: 30s

rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 35672
  virtualhost: /

queueconfig:
  event-exchange: events
  dead-letter-exchange: events.deadletter.exchange
  case-queue: case.rh.case
  case-queue-DLQ: case.rh.case.dlq
  case-routing-key: event.case.update
  uac-queue: case.rh.uac
  uac-queue-DLQ: case.rh.uac.dlq
  uac-routing-key: event.uac.update
  response-authentication-routing-key: event.response.authentication
  qid-filter-prefixes:
     - 11
     - 12
     - 13
     - 14

messaging:
  mismatched-queues-fatal: true
  processing-backoff:
    initial: 5000
    multiplier: 3
    max: 45000
  consuming-threads: 1
  con-max-attempts: 3
  prefetch-count: 1
  recovery-backoff:
    initial: 2000
    multiplier: 3
    max: 30000 
  circuit-breaker:
    timeout: 4
    min-number-of-calls: 100
    sliding-window-size: 100
    failure-rate-threshold: 50
    slow-call-rate-threshold: 100
    writable-stack-trace-enabled: true
    wait-durations-seconds-in-open-state: 60
    slow-call-duration-seconds-threshold: 60
    permitted-number-of-calls-in-half-open-state: 10
    sliding-window-type: COUNT_BASED
    automatic-transition-from-open-to-half-open-enabled: false

swagger-settings:
  swagger-ui-active: true
  group-name: respondenthome-api
  title: RespondentHomeService
  description: API for ${project.artifactId}
  version: ${project.version}

cloud-storage:
  case-schema-name: case
  uac-schema-name: uac
  webform-schema-name: webform
  event-backup-schema-name: event-backup
  backoff:
    initial: 100
    multiplier: 1.2
    max: 16000
    max-attempts: 30
